### PR TITLE
Add client 2.5 and server 10.2.0 to the matrix (most recent releases)

### PR DESCRIPTION
**Pull request by mrow4a**
@tboerger @patrickjahns would be good to have it, for reference to other failing tests (compare logs even)

### CODE REVIEW

**Comment by tboerger** [comment]
This haven't been done intentional, a released server version can't get any fixes, that's why we are only testing stable10 and master branches because these are moving targets which can receive updates/fixes. 

Feel free to test that manually, but it doesn't make sense to test that nightly.

**Comment by mrow4a** [comment]
@tboerger is there somehow a way to trigger theses matrices somehow on demand?

**Comment by tboerger** [comment]
You can use drone exec locally. On the server only the whole matrix permutations can be started.

**Comment by patrickjahns** [comment]
@mrow4a 
What I've done as I didn't want to run this locally, was to create a PR without the intention of merging it 
https://github.com/owncloud/smashbox-testing/pull/8

**Comment by patrickjahns** [comment]
> This haven't been done intentional, a released server version can't get any fixes, that's why we are only testing stable10 and master branches because these are moving targets which can receive updates/fixes.

It would however showcase that a client is breaking for the recent released version and thus the minimal acceptable ownCloud server version would be the next release .....

**Comment by tboerger** [comment]
It will already be showcased and can also be fixed for the release branches. Fixed releases will always stay red every night as it's a fixed release without any moving part that can get fixed by a pull request. So it doesn't make sense to add this here as it would fail every night.

**Comment by mrow4a** [comment]
@patrickjahns @tboerger good idea - we should actually test   - CLIENT_VERSION: master and  SERVER_VERSION: 10.2.0, I will adjust the PR

**Comment by mrow4a** [comment]
closed with https://github.com/owncloud/smashbox-testing/pull/12

**Pull request closed without merging**
