### PR TITLE
Test most recent server release with development master branch of client

### PR DESCRIPTION
**Pull request by mrow4a**
@DeepDiver1975 @patrickjahns @tboerger

### CODE REVIEW

**Comment by tboerger** [comment]
The same argument as before, fine to test against branches, but not against fixed releases as failing tests can't get fixed.

**Comment by mrow4a** [comment]
@tboerger @patrickjahns it tests with client MASTER branch, which changes every day.. If client MASTER branch failed with 10.2 what do you do? Leave it be? Future client version won't be supporting 10.2?

**Comment by tboerger** [comment]
If the server got an issue it's not really fixable...

**Comment by mrow4a** [comment]
It is, correct bug in client master branch. @guruz can you try helping explain here? Would that make sense for you?

**Comment by tboerger** [comment]
And why are the stable10 and master branches not enough???

**Comment by mrow4a** [comment]
@tboerger stable10 is future version to be released... Why are we testing server with released client versions? E.g. server master with client 2.4? 

Following that logic, we should not test released client versions every day.

**Comment by tboerger** [comment]
We are always testing with branches, not tags. That's the difference. Branches can always receive a fix, tags are fixed without any option to provide a fix.

Slowly I'm really out of all this smashbox stuff because it's boring to discuss this over and over again.

**Comment by mrow4a** [comment]
@tboerger master branch can receive a fix

**Comment by tboerger** [comment]
Only on client side.

**Pull request closed without merging**
