### PR TITLE
Add client logs to drone runs for smashbox after test

### PR DESCRIPTION
**Pull request by mrow4a**
@tboerger

### CODE REVIEW

**Comment by tboerger** [comment]
1) this will only work after updating drone to 1.x.x
2) the logs should only be shown in failure case, otherwise we don't need to care about it

**Comment by mrow4a** [comment]
@tboerger yes, I noticed it needs drone 1.x.x. Regarding logs, we can display it as this is no hard to execution time, it just print logs

**Comment by tboerger** [comment]
And it stores the log in the drone database and increases the logs table size even more without any benefit.

**Comment by mrow4a** [comment]
@tboerger legit, thanks

**Pull request closed without merging**
